#if os(Linux)
	import Glibc
#else
	import Darwin
#endif

// Array samle from http://stackoverflow.com/a/24101606
extension Array {
	func sample() -> Element {
		let randomIndex = Int(rand()) % count
		return self[randomIndex]
	}
}

struct Joke {
	let content: String
	static let builtinJokes = [
		"First: Wanted: Swift developer with 5 years experience.",
		"Second: Something...Taylor Swift related?",
		"Third: Keep these jokes coming.",
		"Fourth: Swift: Still not Lisp.",
		"Why is it so hard for women to find men that are sensitive, caring and good-looking?",
		"Because all those men already have boyfriends.",
		"What do electric trains and women's breasts have in common?",
		"They were originally intended for children but it's the men who play with them the most.",
		"Why does it take 100 million sperms to fertilize one egg?",
		"Because they won't stop to ask directions.",
		"What are the three words that men hate to hear during sex?",
		"Are you done?",
		"What are the three words women hate to hear during sex?",
		"Honey, I'm home!",
		"What's the difference between a girlfriend and a wife?",
		"45 pounds.",
		"What's the difference between a boyfriend and a husband?",
		"45 minutes.",
		"What is it when a man talks dirty to a woman?",
		"Sexual harassment.",
		"What is it when a woman talks dirty to a man?",
		"$3.99 a minute.",
		"What do you call a woman who is paralyzed from the waist down?",
		"Married.",
		"What's worse than a male chauvinist pig?",
		"A woman that won't do what she's told.",
		"How can you tell if your wife is dead?",
		"The sex is the same, but the dishes pile up.",
		"How can you tell if your husband is dead?",
		"The sex is the same, but you get the remote.",
		"What's the difference between men and pigs?",
		"Pigs don't turn into men when they drink.",
		"What are those small bumps around a woman's nipples?",
		"What's a man's idea of foreplay?",
		"Half an hour of begging.",
		"What's the best way to make your wife scream when you're having sex?",
		"Call her up and tell her where you are.",
		"Why do husbands die before their wives?",
		"They want to.",
		"Why do women have tits?",
		"So men will talk to them.",
		"Why do women close their eyes during sex?",
		"They can't stand seeing a man have a good time.",
		"Why were men given larger brains than dogs?",
		"So they won't hump female legs at cocktail parties.",
		"Why are hurricanes normally named after women?",
		"When they come they're wild and wet, but when they go they take your house and car with them.",
		"What's the difference between a woman having her period and a terrorist?",
		"You can negotiate with a terrorist",
		"What's the difference between your wife and your job?",
		"After 5 years your job still sucks.",
		"Why are men are like public toilets?",
		"The good ones are taken, the rest are full of shit.",
		"What's the best thing about a blow job?",
		"Ten minutes of silence.",
		"What is the definition of the perfect woman?",
		"A deaf and dumb nympho whose father owns a pub.",
		"What do you call a woman with no asshole?",
		"Divorced or single.",
		"What is the difference between a pregnant woman and a light bulb?",
		"You can unscrew a light bulb.",
		"Did you hear about the new "morning after" pill for men?",
		"It changes their blood type.",
		"What does a woman do with her asshole in the morning?",
		"She makes him a sandwich and sends him to work.",
		"Why do men find it difficult to make eye contact?",
		"Breasts don't have eyes.",
		"How can you tell if your husband is sexually excited?",
		"He's breathing.",
		"What do Kodak film have in common with condoms?",
		"Both capture the moment.",
		"Why do women rub their eyes when they get up in the morning?",
		"Because they don't have balls to scratch.",
		"Why are brides dressed in white?",
		"So they match the rest of the appliances.",
		"What do you do with 365 used condoms?",
		"Re-cycle them into a tyre and call it a Good Year.",
		"Why is pubic hair always curly?",
		"Otherwise it'll poke your eyes.",
		"What's the difference between a slut and a bitch?",
		"A slut will have sex with anyone, a bitch will have sex with anyone but you.",
		"Why is the penis so depress?",
		"His best friends are two nuts who live next to an asshole.",
		"What do you call the useless piece of skin around a vagina?",
		"A woman.",
		"What do you call a man with no arms and no legs, with a ten inch penis?",
		"Partially disabled.",
		"What two things in the air can get a woman pregnant?",
		"Her legs.",
		"What's the difference between worry and panic?",
		"About 28 days.",
		"Why do tampons have strings?",
		"So you can floss after eating.",
		"What's the ultimate rejection?",
		"When you're masturbating and your hand falls asleep.",
		"What is the biggest problem for an atheist during sex?",
		"She's not suppose to yell "Oh God, I'm ..."",
		"How do you get rid of a nun's hiccups?",
		"Tell her she's pregnant.",
		"How do you get a nun pregnant?",
		"Dress her up as a choir boy.",
		"Why do women wear tampons when they skydive?",
		"So they don't whistle on the way down.",
		"What is a man's worst nightmare?",
		"Dolly Parton bottle feeding him.",
		"Which came first? The chicken or the egg?",
		"Neither. The rooster came first.",
		"What is the difference between erotic and kinky?",
		"Erotic is using a feather. Kinky is using the whole chicken.",
		"What do a gynecologist and a pizza delivery guy have in common?",
		"They can smell it but they can't eat it.",
		"How do you determine the sex of your (computer) mouse?",
		"If there's a 'pad' underneath, it's female.",
		"What is the difference between a rectal thermometer and a oral thermometer?",
		"The taste.",
		"What can you assume when you find a lawyer buried up to his neck in cement?",
		"Someone ran out of cement.",
		"What will it take to reunite Nirvana?",
		"Two more bullets.",
		"What did the instructor at the school for Kamikaze pilots say to his students?",
		"Watch closely. I'm only going to do this once.",
		"Why wasn't Jesus born in the U.S.A?",
		"Because God couldn't find three wise men and a virgin.",
		"Why was Jesus a virgin when he died?",
		"Every time he touched a 'wound' it closed.",
		"What is the similarity between Michael Jackson and a grocery bag?",
		"Both are made of plastic and dangerous for children to play with.",
		"What is Michael Jackson's favorite movie?",
		"Honey, I Blew The Kids",
		"Why was Michael Jackson so excited when he first heard about Boyz II Men?",
		"He thought it was a home delivery service.",
		"How many alcoholics does it take to change a light bulb?",
		"Two. One to hold the bulb, and one to drink until the room starts spinning.",
		"Do you know why beer goes through your system so fast?",
		"Because it does not have to stop to change color.",
		"Is it hard to spot the blind guy in a nudist colony?",
		"It's not hard.",
		"How did the blind girl burned the side of her face?",
		"She answered the iron.",
		"How did she burn the other side?",
		"Same guy called back.",
		"How can you tell if a valentine is from a leper?",
		"The tongue's still in the envelope.",
		"What's the most popular pick up line in a gay bar?",
		"May I push in your stool?",
		"Did you hear about the gay security guard who got fired from his job at the sperm bank?",
		"He got caught drinking on the job.",
		"What did one lesbian frog say to the other lesbian frog?",
		"It's true, we really do taste like chicken.",
		"What do you give the blonde that has everything?",
		"Penicillin.",
		"What's six inches long, has a bald head, and drives blondes crazy?",
		"A hundred dollar bill.",
		"What do you say to a blonde with no arms and no legs?",
		"Nice tits!",
		"What does the Bermuda Triangle and blondes have in common?",
		"They've both swallowed a lot of seamen.",
		"What's the difference between a blonde and a guy?",
		"The blonde has the higher sperm count.",
		"What do you call a blonde with two brain cells?",
		"Pregnant.",
		"What do you do when an Irish throws a hand grenade at you?",
		"Pull the pin and throw it back.",
		"What do you do when an Irish throws a pin at you?",
		"Run like hell...he's got a hand grenade in his mouth!",
		"Why did the Irish ice factory close down?",
		"They lost the recipe.",
		"Why did the group of Irish stare at the carton of orange juice?",
		"It said 'concentrate.'",
		"Why don't cannibals eat Irish people?",
		"The last time they threw one in the cooking pot, he ate all the potatoes.",
		"Why don't cannibals eat clowns?",
		"They taste funny.",
		"What do a Rubik's cube and a penis have in common?",
		"The longer you play with them the harder they get.",
		"What did one tampon say to the other tampon?",
		"Nothing, they were both stuck up bitches.",
		"What do you get when you put the energizer bunny's batteries in backward.",
		"He keeps coming and coming and coming.",
		"How do you say virgin in Dutch?",
		"Goodentight.",
		"What is the longest organ in a sheep's body?",
		"A New Zealander's dick.",
		"What do you get when you cross a rooster and a telephone pole?",
		"A twenty-foot cock that wants to reach out and touch someone.",
		"What does the Starship Enterprise and toilet paper have in common?They both circle Uranus looking for cling-ons.",
		"What do the Chicago Cubs and Pee Wee Herman have in common?",
		"They both can't whack it in public.",
		"Did you hear about the midget that went to a nudist colony?",
		"He kept getting in everyone's hair.",
		"What is a Mexican without a lawn mower?",
		"Unemployed.",
		"What is the difference between a Mexican and a bucket of shit?",
		"A bucket.",
		"What do you get when you cross a Mexican and a nigger?",
		"Someone who is too lazy to steal.",
		"What's the hardest thing about fucking a 5 year old?",
		"Having to kill them afterwards.",
		"Old Chinese proverb:",
		"Rape impossible! Woman with skirt up run faster than man with trousers down!",
		"How are airplanes and women alike?",
		"They both have cockpits.",
		"What do you call a smiling Roman with pubic hair between his teeth?",
		"Gladiator!",
		"What is the similarity between a woman and Kentucky Fried Chicken?",
		"By the time you've finished with the breast and thighs, all you have left is a greasy box to put your bone in.",
		"Why do you get paid more at the Sperm Bank than at the Blood Bank?",
		"Sperm is handmade.",
		"What's the difference between a tire and 365 used rubbers?",
		"One is a Goodyear and the other is a great year.",
		"How do you find a blind man in a nudist colony?",
		"It's not hard.",
		"What did the banana say to the vibrator?",
		"What are YOU shaking for? She's going to eat me!",
		"Why don't vampires go south of the border?",
		"Because every time they suck a Mexican's blood, they get the vshits for a month.",
		"Why did they take the "911" numbers off police patrol cars?",
		"Mexicans kept stealing the patrol cars, thinking they were Porsches.",
		"How can you tell when the Mexicans have moved into your neighborhood?",
		"The Blacks get car insurance.",
		"What do you call a Mexican with a vasectomy?",
		"A dry Martinez.",
	]

init(_ content: String) {
	self.content = content
}

// Tells one of our built in jokes
static func tell() -> Joke {
	let joke = Joke(Joke.builtinJokes.sample())
	return joke
	}
}
